### ISSUE TITLE
Datastore upload stuck in a loop

### ISSUE THREAD

**Issue by RJacksonm1** [ckan/ckan#2945]
### CKAN Version if known (or site URL)
CKAN: 2.5.1

Datapusher: stable branch (currently at ckan/datapusher@e2c66697eab21dac8619428d201cc8cfe39a1f37)

Server OS: Debian Jessie

PostgreSQL version: 9.2

### Please describe the expected behaviour

Uploading to datastore (via datapusher) should upload to the datastore?

### Please describe the actual behaviour

When I try to upload a resource from CKAN the datastore API is returning HTTP 409 (conflict) or 500 (a Postgres-related error) to the datapusher, and either datapusher or CKAN is re-queueing the upload job, causing datapusher to get stuck in a perpetual loop trying to push an item into the datastore.

I believe, though I'm not absolutely sure, this this is only happening for resources which have had two upload jobs for the same resource running concurrently, which have conflicted with one another and messed up the relevant database entries.

Pushing a single resource to datapusher appears to work fine, as does re-pushing the same resource.  On one resource I've observed double-clicking the "Upload to Datastore" button (to trigger two simultaneous job requests) causes an infinite loop that has had to be terminated by restarting the web server.

Clicking "Upload to datastore" again on resources which have previously failed due to getting stuck in a loop re-triggers the same upload loop.

### What steps can be taken to reproduce the issue? 

- Upload a resource to CKAN
- Click `Upload to datastore` LOTS
- See if you end up with an infinite loop.

----

You can review the server logs below, for CKAN and datapusher.  I've filtered these down to remove any identifiable information:

[ckan.custom.log.txt](https://github.com/ckan/ckan/files/204682/ckan.custom.log.txt)
[ckan.error.log.txt](https://github.com/ckan/ckan/files/204679/ckan.error.log.txt)
[datapusher.custom.log.txt](https://github.com/ckan/ckan/files/204680/datapusher.custom.log.txt)
[datapusher.error.log.txt](https://github.com/ckan/ckan/files/204681/datapusher.error.log.txt)

These infinite loops end up hogging a significant amount of system resources, which has caused us to put a pause on the CKAN upgrade of an important client of ours (which they are eagerly awaiting).  Any assistance you can offer would be much appreciated.

Thanks

**Comment by wardi** [comment]
Try updating to 2.5.2. This sounds like the first bug fixed in the changelog: https://github.com/ckan/ckan/blob/ckan-2.5.2/CHANGELOG.rst

**Comment by RJacksonm1** [comment]
Ah, that sounds like it might be it!  I'll give that a go.  Sorry for not spotting that myself!

**Comment by RJacksonm1** [comment]
Yep, upgrading to 2.5.2 has resolved this problem!  Thank you!

**Comment by inghamn** [comment]
We are still getting this error after upgrading to 2.5.2

Is there something else we can do?

**Comment by amercader** [comment]
@inghamn Can you provide more details?

Does this happen with all CSV/Excels or with a particular one?
Can you set your logging level to DEBUG and paste the output somewhere?

(please double check that you are indeed running 2.5.2, latest DataPusher and you restarted everthing)

Thanks

**Comment by inghamn** [comment]
We are, indeed, running 2.5.2.

After the upgrade and restart, we were continuing to see the datapusher infinite loop.  Yesterday, I disabled datastore and datapusher.  Today, in order to capture the DEBUG logs, I re-enabled datastore and datapusher......and now, the infinite loop is not happening.

To me it seems most likely that previously pending operations remained that datapusher restarted after the upgrade and reboot.  I am often wrong, though.

**Comment by RJacksonm1** [comment]
I think you're right @inghamn.  When this issue first arose for me I paused the server and reviewed the jobs logged in Datapusher's database.  I had thousands of jobs pending for the same couple of resource. I think it is likely that your datapusher was churning through old jobs.

**Comment by amercader** [comment]
@inghamn Glad to hear it's fixed now. Please let us know if the issue occurs again.
